project:
  type: website
  output-dir: docs

website:
  title: "Learning Azure Storage Non Relational"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - topics.qmd
  sidebar:
    - title: "Home"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - topics.qmd        
        - text: "---"
        - topics/designing-for-data-storage-solution.qmd
        - text: "---"
        - topics/determine-the-best-storage-account-type.qmd
        - text: "---"
        - topics/select-a-storage-replication-strategy.qmd
        - text: "---"
        - topics/determine-the-storage-tier.qmd
        - text: "---"
        - topics/consider-immutable-storage-policies.qmd
        - text: "---"
        - topics/compare-azure-files-to-azure-blobs.qmd
        - text: "---"
        - topics/select-a-file-storage-tier.qmd
        - text: "---"
        - topics/designing-for-netapp-files.qmd
        - text: "---"
        - topics/select-an-azure-disk-solution.qmd
        - text: "---"
        - topics/considerations-for-storage-security.qmd
        - text: "---"
        - topics/hybrid-file-services.qmd
        - text: "---"
        - topics/designing-a-storage-solution-for-tailwind-traders.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
